"""initial schema

Revision ID: 6531dd70b139
Revises: 
Create Date: 2026-09-25 07:59:23.590272+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import promptshield.db.base


# revision identifiers, used by Alembic.
revision: str = '6531dd70b139'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', promptshield.db.base.GUID(), nullable=False),
    sa.Column('email', promptshield.db.base.CIText(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=10), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', promptshield.db.base.TZDateTime(), nullable=False),
    sa.Column('last_login_at', promptshield.db.base.TZDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', promptshield.db.base.GUID(), nullable=False),
    sa.Column('user_id', promptshield.db.base.GUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('ip_address', promptshield.db.base.IPAddress(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('input_hash', sa.Text(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('metadata', promptshield.db.base.JSONBText(), nullable=True),
    sa.Column('created_at', promptshield.db.base.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('inspections',
    sa.Column('id', promptshield.db.base.GUID(), nullable=False),
    sa.Column('user_id', promptshield.db.base.GUID(), nullable=False),
    sa.Column('session_id', promptshield.db.base.GUID(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.Text(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('attack_type', sa.Text(), nullable=True),
    sa.Column('tier_signals', promptshield.db.base.JSONBText(), nullable=True),
    sa.Column('sanitized_text', sa.Text(), nullable=True),
    sa.Column('session_suspicion_score', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('working_model_id', sa.Text(), nullable=False),
    sa.Column('judge_model_id', sa.Text(), nullable=False),
    sa.Column('created_at', promptshield.db.base.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inspections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index('ix_inspections_attack_type', ['attack_type'], unique=False)
        batch_op.create_index('ix_inspections_decision', ['decision'], unique=False)
        batch_op.create_index('ix_inspections_session_id_turn_id', ['session_id', 'turn_id'], unique=False)
        batch_op.create_index('ix_inspections_user_id_created_at', ['user_id', 'created_at'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', promptshield.db.base.GUID(), nullable=False),
    sa.Column('user_id', promptshield.db.base.GUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', promptshield.db.base.TZDateTime(), nullable=False),
    sa.Column('revoked_at', promptshield.db.base.TZDateTime(), nullable=True),
    sa.Column('created_at', promptshield.db.base.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('user_id', promptshield.db.base.GUID(), nullable=False),
    sa.Column('working_model_id', sa.Text(), nullable=True),
    sa.Column('judge_model_id', sa.Text(), nullable=True),
    sa.Column('store_raw_text_in_history', sa.Boolean(), nullable=False),
    sa.Column('tier2_threshold', sa.Float(), nullable=False),
    sa.Column('session_jailbreak_threshold', sa.Float(), nullable=False),
    sa.Column('theme', sa.String(length=10), server_default='auto', nullable=False),
    sa.Column('updated_at', promptshield.db.base.TZDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index('ix_inspections_user_id_created_at')
        batch_op.drop_index('ix_inspections_session_id_turn_id')
        batch_op.drop_index('ix_inspections_decision')
        batch_op.drop_index('ix_inspections_attack_type')

    op.drop_table('inspections')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
